/**
 * Phrases for the "well-wisher friend" persona.
 * Split into Mastered (success) and Retry (guidance) categories.
 */

export const MASTERED_PHRASES = [
    "Great job!",
    "Very good!",
    "Super!",
    "You're on fire!",
    "Excellent work!",
    "Spot on!",
    "You've got this by heart!",
    "Brilliant!",
    "Fantastic!",
    "Wonderful progress!",
    "You're doing amazing!",
    "Perfectly done!",
    "That's the spirit!",
    "Keep it up, champion!",
    "You're a natural!",
    "Masterful!",
    "Impressive memory!",
    "You nailed it!",
    "Outstanding!",
    "Way to go!",
    "You're crushing this!",
    "Incredible focus!",
    "Gold star for you!",
    "You're making this look easy!",
    "Top notch!",
    "Simply superb!",
    "Bravo!",
    "You're unstoppable!",
    "Pure genius!",
    "Love that confidence!",
    "Right on the money!",
    "You're a star student!",
    "Marvelous!",
    "High five!",
    "You're getting so good at this!",
    "That's exactly right!",
    "You're a master in the making!",
    "Spectacular!",
    "So proud of your progress!",
    "You're really shining today!",
    "Unbeatable!",
    "You've mastered this one!",
    "Clear and confident - well done!",
    "Your hard work is paying off!",
    "Solid effort, perfect result!",
    "Keep that momentum going!",
    "You're built for this!",
    "A-plus performance!",
    "You're a knowledge wizard!",
    "Victory is yours!"
];

export const RETRY_PHRASES = [
    "Give it another careful read; we’ll revisit this question.",
    "Take your time and read it again — I’ll ask it once more.",
    "No worries! Let's try this one again in a bit.",
    "Almost there! A quick review will help it stick.",
    "Let's keep this one in the loop for a little longer.",
    "Practice makes perfect! We'll come back to this.",
    "Don't lose heart, let's give it another look together.",
    "Every mistake is a step toward mastery. Reviewing now!",
    "Slow and steady wins the race. Read it once more.",
    "I'll ask this again soon to help you remember.",
    "It's okay! Even the best need a second look sometimes.",
    "Let's refine this one. Read carefully and we'll retry.",
    "A little more focus here will do wonders.",
    "Let's polish this answer together. See you again soon!",
    "Deep breaths! Read it again, and we'll revisit.",
    "Learning takes time. Let's keep this one active.",
    "You're doing great, just need to master this specific one.",
    "Give it one more glance. I'll be back with this question.",
    "Let's solidify this. A quick revisit is coming up.",
    "Don't rush! Read it again to let it sink in.",
    "We'll get this one right next time, I promise!",
    "Keep your chin up! Let's re-study this card.",
    "It's just a hurdle, not a wall. Re-reading helps!",
    "Let's refresh your memory on this one shortly.",
    "Stay positive! We'll tackle this again very soon.",
    "A quick recap, and you'll have it in no time.",
    "Let's keep this card in the 'must-know' pile for now.",
    "Reviewing is the key to success. Let's do it again.",
    "One more read-through will make all the difference.",
    "Persistence pays off! We'll cycle back to this.",
    "It's trial and error. Let's try one more trial.",
    "Let's give this one a second chance to shine.",
    "Focus on the details this time. Re-visiting shortly!",
    "You're learning! Let's re-confirm this one later.",
    "A bit more practice is all you need here.",
    "I believe in you! Let's re-read and try again.",
    "Let's not let this one slip away. Re-asking soon!",
    "Each review makes your brain stronger. Ready for round 2?",
    "Patience is a virtue in learning. Re-reading now.",
    "Let's keep the conversation going on this card.",
    "Small steps lead to big jumps. Let's re-step this one.",
    "Almost caught it! Let's throw the question again later.",
    "It's on the tip of your tongue! Let's review to be sure.",
    "Constructive repetition! We'll be back for this.",
    "Let's strengthen this connection in your memory.",
    "Honesty is the first step to learning. Re-trying soon!",
    "A moment of focus now saves a lot of time later.",
    "Let's bridge the gap on this one. Re-reading...",
    "Your friend is here to help! Let's look at this again.",
    "Final check is coming soon. Give it a good read now!"
];

export const getRandomPhrase = (category) => {
    const list = category === 'mastered' ? MASTERED_PHRASES : RETRY_PHRASES;
    return list[Math.floor(Math.random() * list.length)];
};
